services:
  mongo:
    image: mongo
    container_name: bloglist-mongo
    volumes:
      - ./bloglist-backend/mongo_data:/data/db
  backend:
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
    container_name: bloglist-backend
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@localhost:3456/the_database npm run dev
      - PORT=3003
    depends_on:
      - mongo
    volumes:
      - ./bloglist-backend:/usr/src/app

  frontend:
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    container_name: bloglist-frontend
    depends_on:
      - backend
    volumes:
      - ./bloglist-frontend:/usr/src/app

  nginx:
    image: nginx:1.20.1
    container_name: bloglist-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend